# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
url:            "http://localhost:9001"
encoding:       UTF-8

site:
  url: "http://localhost:9001"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
  